### ISSUE TITLE
🦟 [Bugfix] Older 32 bit Android  devices can't handle the change to bech32

### ISSUE THREAD

**Issue by kcw-grunt** [litecoin-foundation/loafwallet-core#22]
### Problem
When migrating the `loafwallet-core` to bech32 there is a class and method that remaps the memory spacing.  Older phones cannot take the updates because the mapping causes the database to lose the data.

### Goal
Ugrade the library `loafwallet-core` so that older phones like Samsung J2 and Samsung J7 can manage the onboard database given the newer memory mapping.

## Background 
https://github.com/litecoin-foundation/loafwallet-core/pull/19
https://github.com/litecoin-foundation/loafwallet-android/issues/240

### Contact
Please contact @kcw-grunt for more background

### Bounty
We are offering $500 for this bug fix in Litecoin.  We are [non-profit ](https://litecoin-foundation.org)and this is quite alot for our budget but it will help thousands of users.

**Comment by kcw-grunt** [comment]
cc: @losh11 , @coblee , @mosadialiou

**Comment by losh11** [comment]
I will make reproducible branches available for anyone able to help.

**Comment by kcw-grunt** [comment]
> I will make reproducible branches available for anyone able to help.
> […](#)

Thanks @losh11

**Comment by kcw-grunt** [comment]
Closing this as we will redress this issue given the Litewallet Android code is upgraded by @vsima .
